### ISSUE TITLE
sidebar is centered

### ISSUE THREAD

**Issue by npit** [sakibccr/pristine#2]
Example site renders the sidebar centered in the webpage. I'm using  hugo 0.46.
Screengrab [here](http://i68.tinypic.com/10rtt2h.png)

**Comment by sakibccr** [comment]
Hi,

Could you please check if `baseURL` variable was set correctly in your config file? Also could you please report the version of the browser you are using?

Thanks.

**Comment by npit** [comment]
I am running the site locally from the exampleSite folder, so the baseURL shouldn't make a difference.
I am using the latest chromium ( 68.0.3440.106 )

**Comment by sakibccr** [comment]
I am unable to reproduce this. I have the same browser.

If you use `hugo serve` command with whatever set as `baseURL`, sidebar should appear as intended. But if you build the site using `hugo` command and serve the built site, and your `baseURL` is not set correctly, the site displays as broken.

So if you get the error in a built site, please check your `baseURL`. If not, could you please provide a screenshot of chrome dev tools? Steps to get the screenshot are these:

1. Open the broken page in chromium.
2. Press Ctrl+Shift+i and you will get the dev tools.
3. Select the Console tab.
4. Take a screenshot of the content of that tab.

As you are getting a broken page, I am assuming it's because some CSS file is not loading. We should get some idea about this from the screenshot.

Thank you very much.

**Comment by npit** [comment]
Thanks for the swift reply.
>  I am assuming it's because some CSS file is not loading. We should get some idea about this from the screenshot.

Seems you're right, [screengrab](http://i68.tinypic.com/2cem002.png) .
**edit:**  img host link does not load, pasting content here as well:
>localhost/:1 Refused to apply style from 'http://localhost:1313/css/magnific-popup.css' because its MIME type ('text/plain') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
localhost/:110 GET http://localhost:1313/js/jquery-1.11.2.min.js 404 (Not Found)
localhost/:111 GET http://localhost:1313/js/main.js 404 (Not Found)
localhost/:114 GET http://localhost:1313/js/jquery.magnific-popup.min.js 404 (Not Found)
(index):110 GET http://localhost:1313/js/jquery-1.11.2.min.js 404 (Not Found)
(index):1 Refused to execute script from 'http://localhost:1313/js/jquery-1.11.2.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
(index):111 GET http://localhost:1313/js/main.js 404 (Not Found)
(index):1 Refused to execute script from 'http://localhost:1313/js/main.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
(index):114 GET http://localhost:1313/js/jquery.magnific-popup.min.js 404 (Not Found)
(index):1 Refused to execute script from 'http://localhost:1313/js/jquery.magnific-popup.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.

**Comment by sakibccr** [comment]
Hi @npit 

The only way I could replicate the issue was to remove/rename the css/js files in question from the static dir.

Could you please make sure that the directory `themes/pristine/static` contains three directories called `css`, `img`, `js` and they have the relevant files?

For example, if `themes/pristine/static/js/main.js` doesn't exist, you will see errors like this:
```(index):1 Refused to execute script from 'http://localhost:1313/js/main.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.```

Which is what you are getting. So could you please make sure that after you cloned the theme the files were not renamed or replaced?

Thank you very much.

**Comment by npit** [comment]
> The only way I could replicate the issue was to remove/rename the css/js files in question from the static dir.

You're right, and that was the case. The js and css folders were missing in the exampleSite/static.
Thanks a bunch @sakibccr !
